## This file should only be updated in the coding-standards (https://github.com/PaddleHQ/coding-standards/) repo.
## Changes will automatically generate a PR into all the go services and libraries

version: "2"
run:
  tests: true

severity:
  default: notice

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  exclusions:
    paths:
      - third_party$
      - builtin$
      - examples$

linters:
  default: none
  enable:
    - nilnil
    - wrapcheck
  settings:
    wrapcheck:
      ignore-package-globs:
        - github.com/PaddleHQ/*
  exclusions:
    rules:
      - linters:
          - nilnil
          - wrapcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
