## This file should only be updated in the coding-standards (https://github.com/PaddleHQ/coding-standards/) repo.
## Changes will automatically generate a PR into all the go services and libraries

run:
  tests: true

severity:
  default-severity: notice

issues:
  exclude-use-default: false
  exclude-generated: "strict"
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - nilnil
        - wrapcheck

linters-settings:
  wrapcheck:
    ignorePackageGlobs:
      - github.com/PaddleHQ/*

linters:
  enable:
    # Checks for no simultaneous return of nil error and an invalid value: https://github.com/Antonboom/nilnil
    - nilnil
    # Checks that errors returned from external packages are wrapped: https://github.com/tomarrell/wrapcheck
    - wrapcheck
